// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data.Data;

#nullable disable

namespace MyApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125165456_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices, gadgets, and smart technology products.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fashion apparel for men, women, and children.",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Household essentials, cookware, and home accessories.",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sporting goods, fitness equipment, and outdoor gear.",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Printed and digital books across various genres.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cosmetics, skincare, and beauty care products.",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Toys, games, and educational products for kids.",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Car accessories, maintenance supplies, and tools.",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Everyday food items, beverages, and household necessities.",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fashion accessories including bags, belts, and jewelry.",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("MyApp.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest-gen smartphone with high-end features.",
                            Name = "Smartphone X",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Noise-cancelling over-ear headphones.",
                            Name = "Wireless Headphones",
                            Price = 199.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "100% cotton casual t-shirt.",
                            Name = "Men's T-Shirt",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Durable non-stick cookware for everyday use.",
                            Name = "Non-Stick Frying Pan",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Anti-slip fitness mat for workouts.",
                            Name = "Yoga Mat",
                            Price = 25.75m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Bestselling adventure fantasy book.",
                            Name = "Fantasy Novel",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Description = "Hydrating skincare cream for daily use.",
                            Name = "Face Moisturizer",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Description = "Colorful puzzle set for early learning.",
                            Name = "Kids Puzzle Set",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Description = "Dashboard mount for smartphones.",
                            Name = "Car Phone Mount",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            Description = "Extra virgin olive oil for cooking.",
                            Name = "Organic Olive Oil",
                            Price = 7.99m
                        });
                });

            modelBuilder.Entity("MyApp.Data.Entities.Product", b =>
                {
                    b.HasOne("MyApp.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApp.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
